# Generated by Django 2.2 on 2021-04-30 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directory_id', models.IntegerField(help_text='Directory ID which the owner of the account', unique=True)),
                ('login', models.CharField(help_text='Users login', max_length=50, unique=True)),
                ('password', models.CharField(help_text='Users password', max_length=100)),
                ('types', models.CharField(choices=[('user', 'Standard User'), ('administrator', 'Administrator User'), ('super_user', 'Super Administrator User')], default='user', help_text='Users account type [user, administrator, super_user]', max_length=20)),
                ('status', models.IntegerField(default=1, help_text='Users accout status [blocked or unlocked]')),
                ('administrator', models.CharField(help_text='Users who create the account', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Account creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last date of update', null=True)),
            ],
            options={
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
        ),
    ]
