# Generated by Django 2.2 on 2021-04-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='types',
            field=models.CharField(choices=[('user', 'Standard User'), ('administrator', 'Administrator User'), ('super_user', 'Super Administrator User')], max_length=20),
        ),
    ]
