# Generated by Django 2.2 on 2021-05-19 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_sessionhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessionhistory',
            options={'ordering': ['-created_at']},
        ),
    ]
