# Generated by Django 2.2 on 2021-05-19 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210519_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionhistory',
            name='logged',
            field=models.BooleanField(choices=[(True, 'Connected'), (False, 'Disconnected')], default=True),
        ),
    ]
