# Generated by Django 2.2 on 2021-05-20 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210519_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionhistory',
            name='logged',
        ),
    ]
