# Generated by Django 2.2 on 2021-06-18 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_sessionhistory_logged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionhistory',
            name='user_agent',
            field=models.CharField(max_length=255),
        ),
    ]
