# Generated by Django 2.2 on 2021-06-18 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0003_auto_20210618_2128'),
        ('users', '0006_auto_20210618_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='directory_id',
        ),
        migrations.AddField(
            model_name='user',
            name='directory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='directories.Directory'),
            preserve_default=False,
        ),
    ]
