# Generated by Django 2.2 on 2021-06-18 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210618_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='directory',
        ),
        migrations.AddField(
            model_name='user',
            name='directory_id',
            field=models.IntegerField(default=0, help_text='Directory ID which the owner of the account', unique=True),
            preserve_default=False,
        ),
    ]
