# Generated by Django 2.2 on 2021-04-30 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('serial_number', models.CharField(max_length=50)),
                ('modele', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('unity', models.CharField(choices=[('pcs', 'Piece'), ('cartoon', 'Carton'), ('box', 'Boite'), ('kg', 'Kg'), ('g', 'Gramme'), ('L', 'Litre'), ('m', 'Metre')], max_length=50)),
                ('state', models.CharField(choices=[('new', 'Nouveau'), ('occasion', 'Occasion'), ('hs', 'Hors service')], max_length=10)),
                ('fournissor', models.CharField(max_length=50, null=True)),
                ('fournissor_contact', models.CharField(blank=True, max_length=30)),
                ('administrator', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'materials',
            },
        ),
        migrations.CreateModel(
            name='MouvmentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('product_id', models.IntegerField(null=True)),
                ('description', models.TextField(null=True)),
                ('note', models.TextField(null=True)),
                ('quantity', models.IntegerField()),
                ('unity', models.CharField(max_length=20)),
                ('types', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=10)),
                ('administrator', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'mouvment_history',
            },
        ),
    ]
