# Generated by Django 2.2 on 2021-01-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('unity', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=10)),
                ('administrator', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'materials',
            },
        ),
        migrations.CreateModel(
            name='MouvmentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('product_id', models.IntegerField()),
                ('description', models.TextField(null=True)),
                ('note', models.TextField(null=True)),
                ('quantity', models.IntegerField()),
                ('unity', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=10)),
                ('administrator', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'mouvment_history',
            },
        ),
    ]
