# Generated by Django 2.2 on 2021-01-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouvmenthistory',
            name='product_id',
            field=models.IntegerField(null=True),
        ),
    ]
