# Generated by Django 2.2 on 2021-04-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='state',
            field=models.CharField(choices=[('new', 'Nouveau'), ('occasion', 'Occasion')], max_length=10),
        ),
        migrations.AlterField(
            model_name='materials',
            name='unity',
            field=models.CharField(choices=[('pcs', 'Piece'), ('cartoon', 'Carton'), ('box', 'Boite'), ('kg', 'Kg'), ('g', 'Gramme'), ('L', 'Litre'), ('m', 'Metre')], max_length=50),
        ),
    ]
