# Generated by Django 2.2 on 2021-05-20 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_auto_20210519_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mouvmenthistory',
            name='title',
        ),
    ]
