# Generated by Django 2.2 on 2021-01-25 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_auto_20210121_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materials',
            name='type',
        ),
    ]
