# Generated by Django 2.2 on 2021-03-30 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_remove_materials_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mouvmenthistory',
            old_name='type',
            new_name='types',
        ),
        migrations.AddField(
            model_name='materials',
            name='fournissor',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='materials',
            name='fournissor_contact',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='materials',
            name='modele',
            field=models.CharField(default='OKGSG-67', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materials',
            name='serial_number',
            field=models.CharField(default='THD9-HGD', max_length=50),
            preserve_default=False,
        ),
    ]
