# Generated by Django 2.2 on 2021-05-20 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_remove_mouvmenthistory_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouvmenthistory',
            name='types',
            field=models.CharField(choices=[('entry', 'Entree'), ('takeout', 'Sortie'), ('edit', 'Edition')], max_length=50),
        ),
    ]
