# Generated by Django 2.2 on 2021-05-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_auto_20210520_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvmenthistory',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
