# Generated by Django 2.2 on 2021-05-20 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0006_mouvmenthistory_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mouvmenthistory',
            old_name='title',
            new_name='product_name',
        ),
    ]
