# Generated by Django 2.2 on 2021-06-18 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0007_auto_20210520_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouvmenthistory',
            name='state',
            field=models.CharField(choices=[('new', 'Nouveau'), ('occasion', 'Occasion'), ('out_of_service', 'Hors service'), ('out_of_service_reparable', 'Hors service reparable')], max_length=10),
        ),
    ]
