# Generated by Django 2.2 on 2021-04-30 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('man', 'Homme'), ('woman', 'Femme'), ('other', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=50)),
                ('cin', models.CharField(max_length=20)),
                ('delivered_on', models.DateField()),
                ('delivered_at', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=30)),
                ('urgent_phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=100)),
                ('function', models.CharField(max_length=100)),
                ('departement', models.CharField(max_length=20)),
                ('date_of_service', models.DateField()),
                ('end_of_service', models.DateField(null=True)),
                ('matricule_number', models.CharField(max_length=10)),
                ('state', models.IntegerField(choices=[(1, 'En service'), (2, 'En Pause'), (3, 'En permission'), (4, 'En conge'), (0, 'Hors service')], default=1)),
                ('avatar', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('administrator', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'directories',
            },
        ),
    ]
