# Generated by Django 2.2 on 2021-06-30 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0003_auto_20210618_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='soldes',
            field=models.IntegerField(default=30, help_text='Total solde of the year'),
        ),
    ]
