# Generated by Django 2.2 on 2021-03-31 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50, verbose_name='computers description')),
                ('state', models.CharField(max_length=20)),
                ('serial_number', models.CharField(max_length=30)),
                ('modele', models.CharField(max_length=30, verbose_name='the modele of computer')),
                ('mark', models.CharField(max_length=50)),
                ('os', models.CharField(max_length=20, verbose_name='operating system')),
                ('processor', models.CharField(max_length=10)),
                ('processor_generation', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=30, verbose_name='category of computer')),
                ('ram', models.IntegerField()),
                ('type_of_ram', models.CharField(max_length=10)),
                ('fournissor', models.CharField(max_length=50)),
                ('fournissor_contact', models.CharField(max_length=30)),
                ('assigned_to', models.CharField(max_length=50, null=True, verbose_name='is assigned')),
                ('assigned_at', models.DateField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date of last update')),
            ],
            options={
                'verbose_name': 'Computers',
                'verbose_name_plural': 'Computers',
                'db_table': 'computers',
            },
        ),
    ]
