# Generated by Django 2.2 on 2021-03-05 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='computers',
            name='state',
            field=models.CharField(default='new', max_length=20),
            preserve_default=False,
        ),
    ]
