# Generated by Django 2.2 on 2021-03-06 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0002_computers_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='computers',
            name='name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
