# Generated by Django 2.2 on 2021-04-03 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0002_auto_20210401_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='computers',
            name='administrator',
            field=models.CharField(default='superuser', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='computers',
            name='category',
            field=models.CharField(choices=[('laptop', 'Laptop'), ('desktop', 'Desktop'), ('mbp', 'MacBook Pro'), ('mbp_retina', 'MacBook Pro Retina'), ('notebook', 'Notebook')], max_length=30, verbose_name='category of computer'),
        ),
    ]
