# Generated by Django 2.2 on 2021-04-03 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0003_auto_20210403_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='computers',
            name='status',
            field=models.CharField(choices=[('assigned', 'Attribue'), ('not_assigned', 'Non attribue'), ('on_suspens', 'En suspens'), ('out_of_service', 'Hors service')], default='assigned', max_length=20),
            preserve_default=False,
        ),
    ]
