# Generated by Django 2.2 on 2021-03-19 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0004_auto_20210306_1904'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='computers',
            options={'verbose_name': 'Computers', 'verbose_name_plural': 'Computers'},
        ),
    ]
