# Generated by Django 2.2 on 2021-06-18 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0004_allocationhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computers',
            name='status',
            field=models.CharField(choices=[('assigned', 'Attribue'), ('not_assigned', 'Non attribue'), ('on_suspens', 'En suspens'), ('out_of_service', 'Hors service'), ('out_of_service_reparable', 'Hors service reparable')], max_length=20),
        ),
    ]
