# Generated by Django 2.2 on 2021-05-20 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directory_id', models.IntegerField(help_text='The ID of person who does the request')),
                ('types', models.CharField(choices=[('MVCT', 'Maternity Vacation'), ('PVCT', 'Peternity Vacation'), ('SVCT', 'Sickness Vacation'), ('PRM', 'Permission'), ('FRM', 'Formation'), ('OTH', 'Other')], help_text='Type of the absence (vacation|permission|external formation|other)', max_length=20)),
                ('begin_date', models.DateField(help_text='Beginning date of the absence')),
                ('end_date', models.DateField(help_text='Ending date of the absence')),
                ('interim', models.CharField(help_text='The interim person', max_length=50, null=True)),
                ('interim_contact', models.CharField(help_text='The interim contact', max_length=50, null=True)),
                ('reasons', models.TextField(help_text='The reasons of absence')),
                ('status', models.IntegerField(choices=[(0, 'Waiting'), (1, 'Waiting for second validation'), (2, 'Validated'), (3, 'Abandoned'), (4, 'Rejected')], default=0, help_text='The status of absence if it is done = 1 or doing = 0 or abandoned = 2')),
                ('validator_1', models.CharField(help_text='The first responsible who valide the absence', max_length=50, null=True)),
                ('first_validation_at', models.DateTimeField(help_text='Date of the first validation', null=True)),
                ('validator_2', models.CharField(help_text='The second responsible who valide the absence', max_length=50, null=True)),
                ('second_validation_at', models.DateTimeField(help_text='Date of second validation and the last validation', null=True)),
                ('justificative', models.CharField(help_text='Justivicative piece [optional]', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date of request')),
                ('updated_at', models.DateTimeField(default=None, help_text='Date of last update', null=True)),
            ],
            options={
                'db_table': 'absences',
                'ordering': ['-created_at'],
            },
        ),
    ]
