# Generated by Django 2.2 on 2021-03-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absences',
            name='begin_date',
            field=models.DateField(help_text='Beginning date of the absence'),
        ),
        migrations.AlterField(
            model_name='absences',
            name='status',
            field=models.IntegerField(choices=[(0, 'Waiting'), (1, 'Waiting for second validation'), (2, 'Validated'), (3, 'Abandoned'), (4, 'Rejected')], default=0, help_text='The status of absence if it is done = 1 or doing = 0 or abandoned = 2'),
        ),
    ]
