# Generated by Django 2.2 on 2021-06-30 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='soldes',
            field=models.IntegerField(default=30, help_text='Total solde of the year'),
        ),
    ]
