# Generated by Django 2.2 on 2021-06-30 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('absences', '0002_absence_soldes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absence',
            name='soldes',
        ),
    ]
